apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multicontainer-pod1
  name: multicontainer-pod1
spec:

  volumes:
  - name: shared-data
    emptyDir: {}

  containers: 
  - image: attgua/python-write:0.15
    name: python-write
    volumeMounts:
    - name: shared-data
      mountPath: /home
    args:
    - bin/sh
    - -c
    - cp app/main.py home/main.py ; cp app/requirements.txt home/requirements.txt ; cp usr/local/bin/flask /home/flask ; sleep 3600

  - name: python-execute
    ports:
    - containerPort: 5000
    resources: {}
    volumeMounts:
    - name: shared-data
      mountPath: /app
    image: attgua/python-execute:0.15
    args:
    - /bin/sh
    - -c
    - cp /app/flask /usr/local/bin/flask; pip3 install -r /app/requirements.txt; python3 /app/main.py ; sleep 3600
  restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: multicontainer-pod1
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer