apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multicontainer-pod1
  name: multicontainer-pod1

spec:
  volumes:
  - name: shared-data
    emptyDir: {}

  initContainers: 
  - image: attgua/python-write:0.15
    name: python-write
    volumeMounts:
    - name: shared-data
      mountPath: /home
    args:
    - bin/sh
    - -c
    - cp -r app/* home ; pip3 install -r /app/requirements.txt -t /home/req;

  containers:
  - name: python-execute
    ports:
    - containerPort: 5000
    resources: {}
    volumeMounts:
    - name: shared-data
      mountPath: /app
    image: attgua/python-execute:0.15
    args:
    - /bin/sh
    - -c
    - cp -r /app/req/* /usr/local/lib/python3.10/site-packages; python3 /app/main.py ; sleep 3600
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: multicontainer-service
spec:
  selector:
    run: multicontainer-pod1
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
    nodePort: 30992

  type: LoadBalancer

