apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: |-
    {{- range .Values.roleDeveloper.namespaces }}
    - {{ . | quote }}
    {{- end }}    # developement
  name: developer
rules:
- apiGroups: ["", "extensions", "app"]
  resources: ["deployments","replicasets", "pods"]
  verbs: ["list", "get", "watch", "create" , "update", "patch", "delete"]